// <auto-generated />
namespace StarSecurityService.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class editdatabasecandidate1508 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editdatabasecandidate1508));
        
        string IMigrationMetadata.Id
        {
            get { return "202108151505271_edit-database-candidate-1508"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
