// <auto-generated />
namespace StarSecurityService.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateBranch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateBranch));
        
        string IMigrationMetadata.Id
        {
            get { return "202108171303216_updateBranch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
