// <auto-generated />
namespace StarSecurityService.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_foreginkey_vacancy_and_addrequriement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_foreginkey_vacancy_and_addrequriement));
        
        string IMigrationMetadata.Id
        {
            get { return "202108031500294_Add_foreginkey_vacancy_and_addrequriement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
