// <auto-generated />
namespace StarSecurityService.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatemigrationemployyee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatemigrationemployyee));
        
        string IMigrationMetadata.Id
        {
            get { return "202108080350016_update-migration-employyee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
